### ISSUE TITLE
 HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by tringler** [danielperna84/hass-poc-configurator#2]
Hello,

if the solution is trying to get the bootstrap information I get:
```
192.168.178.102 - - [29/Jan/2017 22:04:36] "GET / HTTP/1.1" 200 -
HTTP Error 403: Forbidden
<urlopen error [Errno -2] Name or service not known>
192.168.178.102 - - [29/Jan/2017 22:04:36] "GET /api/files HTTP/1.1" 200 -
192.168.178.102 - - [29/Jan/2017 22:04:37] "GET /favicon.ico HTTP/1.1" 200 -
HTTP Error 403: Forbidden
<urlopen error [Errno -2] Name or service not known>
192.168.178.102 - - [29/Jan/2017 22:05:13] "GET / HTTP/1.1" 200 -
HTTP Error 403: Forbidden
<urlopen error [Errno -2] Name or service not known>
192.168.178.102 - - [29/Jan/2017 22:05:13] "GET /api/files HTTP/1.1" 200 -
192.168.178.102 - - [29/Jan/2017 22:05:13] "GET /favicon.ico HTTP/1.1" 200 -
HTTP Error 403: Forbidden
<urlopen error [Errno -2] Name or service not known>
```

But the API itself is working, because I can restart the HASS service i.e.

I also tried to harcode it here without any success:
```
        boot = "{}"
        try:
            response = urllib.request.urlopen("https://192.168.178.200:443/api/bootstrap")
            boot = response.read().decode('utf-8')
        except Exception as err:
            print(err)
```

**Comment by danielperna84** [comment]
I have updated the configurator.py shortly after publishing the release (if that's the version you are using). There it should be fixed already. Could you please test?

**Comment by tringler** [comment]
I updated to the last commit, but the problem still persists - The credentials are also not working. I set it up like this: `CREDENTIALS = "tringler:89iokl12qwa1!89iokl1!"`

**Comment by danielperna84** [comment]
For the API error:
`<urlopen error [Errno -2] Name or service not known>` tells us, that it's failing accessing the API under that address. If you copy and paste the URL (https://192.168.178.200:443/api/bootstrap) into your browser, to you get a response with JSON-output?

For the credentials:
If you look at the log of the service, are there messages looking like
```
192.168.1.30 - - [30/Jan/2017 00:15:07] "GET /api/files HTTP/1.1" 200 -
192.168.1.30 - - [30/Jan/2017 00:15:07] "GET /favicon.ico HTTP/1.1" 200 -
Requesting authorization
192.168.1.30 - - [30/Jan/2017 00:15:27] "GET / HTTP/1.1" 401 -
Requesting authorization
192.168.1.30 - - [30/Jan/2017 00:15:31] "GET / HTTP/1.1" 401 -
192.168.1.30 - - [30/Jan/2017 00:15:35] "GET / HTTP/1.1" 200 -
```
The focus is on the 401 errors and the resulting `Requesting authorization`.

**Comment by tringler** [comment]
If I request [](https://192.168.178.200:443/api/bootstrap ) via browser I get `403: Forbidden` instead of a JSON output, but this also applies to `https://192.168.178.200/api`so I assumed this just because of I didn't send any autorization HTTP header with the request.

**Comment by danielperna84** [comment]
1. Great that's resolved now.
2. That's wierd. Do you get the popup to enter the username and password and it just doesn't accept what you enter? The up 2 date code is [configurator.py](https://github.com/danielperna84/hass-poc-configurator/blob/master/configurator.py), and there in line 470 it's told to explicitly print it out when authentication is required (the requesting authorization message).

**Comment by tringler** [comment]
Not at all! 
Indeed, my first idea was that I'm using a version in which the authentication is not implemented yet. I don't understand it: I hardcoded it with:

```
def run():
    global CREDENTIALS
    print('Starting server')
    server_address = (LISTENIP, LISTENPORT)
    CREDENTIALS = base64.b64encode(bytes(CREDENTIALS, "utf-8"))
    print(CREDENTIALS)
    Handler = AuthHandler
    httpd = socketserver.TCPServer(server_address, RequestHandler)
    httpd.socket = ssl.wrap_socket(httpd.socket, certfile=SSL_CERTIFICATE, keyfile=SSL_KEY, server_side=True)
    print('Listening on: %s://%s:%i' % ('https' if SSL_CERTIFICATE else 'http', LISTENIP, LISTENPORT))
    if BASEPATH:
        os.chroot(BASEPATH)
        os.chdir('/')
    httpd.serve_forever()

run()
```
and
```
class AuthHandler(RequestHandler):
    def do_HEAD(self):
        self.send_response(200)
        print ("fancy authhandler")
        self.send_header('Content-type', 'text/html')
        self.end_headers()
```

I never see `fancy authhandler` in my log and no login/password prompt.

**Comment by danielperna84** [comment]
Uhm, the AuthHandler looks like this for me:

```python
class AuthHandler(RequestHandler):
    def do_AUTHHEAD(self):
        print("Requesting authorization")
        self.send_response(401)
        self.send_header('WWW-Authenticate', 'Basic realm=\"HASS-PoC-Configurator\"')
        self.send_header('Content-type', 'text/html')
        self.end_headers()
```

So you still have the `do_HEAD` method in there. That was removed with commit 62bb62cbab0904c41b4ec42e0a36bfe26f2545ec 19 hours ago.

**Comment by tringler** [comment]
Currently for testings I'm starting the script via console - I don't get it. I updated to the last version of the code, but logging is still:
```

Starting server
AuthHandler
Listening on: https://192.168.178.200:3218
192.168.178.102 - - [30/Jan/2017 21:21:02] "GET / HTTP/1.1" 200 -
<urlopen error [Errno -2] Name or service not known>
192.168.178.102 - - [30/Jan/2017 21:21:02] "GET /api/files HTTP/1.1" 200 -
192.168.178.102 - - [30/Jan/2017 21:21:03] "GET /favicon.ico HTTP/1.1" 200 -
<urlopen error [Errno -2] Name or service not known>
```

The AuthHandler line is created because of:
```
   if CREDENTIALS:
        CREDENTIALS = base64.b64encode(bytes(CREDENTIALS, "utf-8"))
        Handler = AuthHandler
        print ('AuthHandler')
```

Which should say, that the AuthHandler class should be instanced and at least I should get `        print("Requesting authorization")`

**Comment by danielperna84** [comment]
Since this is totally wierd, I think we should handle this step by step.
On the machine you're running this on switch do the following:
```bash
cd /tmp
curl -O https://raw.githubusercontent.com/danielperna84/hass-poc-configurator/master/configurator.py
md5um configurator.py
# this should return the following hash: 41680d54c6550738319dc68a0980800e
chmod 755 configurator.py
```
After that, set the `BASEPATH` to match your HASS-directory and enter the credentials. Leave everything else as it is. For now we just want to make sure you get the login-box, so it doesn't matter if the API or anything else is working.

**Comment by tringler** [comment]
Here you go with the complete logging what I did:
```

root@elfriede:/etc/homeassistant# cd /tmp
root@elfriede:/tmp# curl -O https://raw.githubusercontent.com/danielperna84/hass-poc-configurator/master/configurator.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19994  100 19994    0     0  32452      0 --:--:-- --:--:-- --:--:-- 32510
root@elfriede:/tmp# md5um configurator.py
-bash: md5um: Kommando nicht gefunden.
root@elfriede:/tmp# md5sum configurator.py
41680d54c6550738319dc68a0980800e  configurator.py
root@elfriede:/tmp# chmod 755 configurator.py
root@elfriede:/tmp# nano configurator.py
root@elfriede:/tmp# /usr/bin/python3 configurator.py
Starting server
Listening on: http://0.0.0.0:3218
192.168.178.102 - - [30/Jan/2017 21:46:17] "GET / HTTP/1.1" 200 -
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 0] Error>
192.168.178.102 - - [30/Jan/2017 21:46:17] "GET / HTTP/1.1" 200 -
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 0] Error>
192.168.178.102 - - [30/Jan/2017 21:46:18] "GET /api/files HTTP/1.1" 200 -
192.168.178.102 - - [30/Jan/2017 21:46:19] "GET /favicon.ico HTTP/1.1" 200 -
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 0] Error>
```

This is my current [configurator.py](https://gist.github.com/tringler/0f5f190f26ed956510ee242c12171339) - I just modified the `BASEPATH`

**Comment by danielperna84** [comment]
I assume you have the `CREDENTIALS` set locally, even though that's not in the gist? And just for testing: use something really simple like `"test:test"`. I haven't tested it with special characters.

**Comment by tringler** [comment]
Oh - My fault! Now I get the login prompt! I will now try to my settings step-by-step and see where it fails.

**Comment by tringler** [comment]
It looks like that as soon as I use:
```
SSL_CERTIFICATE = "/etc/homeassistant/ha-cert.crt"
SSL_KEY = "/etc/homeassistant/ha-cert.key"
```

I'm not getting the authentication prompt. Is this maybe caused by my outdated cert?

**Comment by danielperna84** [comment]
I have to admit that I haven't tested it with SSL. I just tested SSL alone, but then turned it off again when implementing the authentication. Will have a look at it now.

**Comment by danielperna84** [comment]
Does everything besides authentication work with the certificate you are using?

**Comment by tringler** [comment]
Entities are loaded, Services are loaded, I can edit/save files and I can restart HASS so I would say yes.

**Comment by danielperna84** [comment]
I found it [here](https://github.com/danielperna84/hass-poc-configurator/blob/master/configurator.py#L518)!
The else-case was still using the regular RequestHandler.

**Comment by tringler** [comment]
Yes! 👍 
I confirm it's working with:
```
    else:
        httpd = socketserver.TCPServer(server_address, Handler)
        httpd.socket = ssl.wrap_socket(httpd.socket, certfile=SSL_CERTIFICATE, keyfile=SSL_KEY, server_side=True)
    print('Listening on: %s://%s:%i' % ('https' if SSL_CERTIFICATE else 'http', LISTENIP, LISTENPORT))
````

**Comment by danielperna84** [comment]
I've pushed the latest code (which also includes a new feature: ALLOWED_NETWORKS).

Are all those urlopen errors gone now as well or do they persist?

**Comment by tringler** [comment]
By the way, IP-BAN based on failed login attempts would be also nice features.

No, I still getting `<urlopen error [Errno -2] Name or service not known>`

**Comment by danielperna84** [comment]
Yeah, I'll have a look at that.

Hhmm, wonder where those are coming from. Since they don't impact functionality that would have a low priority. If you want to, you could fill up the could with a ton of `print` statements to locate where in the code this is happening.

**Comment by tringler** [comment]
HASS Restart seems to not working anymore - Are you sure `api/restart` is valid? I'm getting:
`404: Not Found` if I type `https://HASS/api/restart` in the browser

**Comment by danielperna84** [comment]
The `api/restart` does not connect to HASS, but to the configurator. The configurator then internally connects to `abcd:8123/api/services/homeassistant/restart`. I'll check that.

**Comment by tringler** [comment]
I see - I can imagine this is not working:
```
                if HASS_API_PASSWORD:
                    headers["x-ha-access"] = HASS_API_PASSWORD
                req = urllib.request.Request("%sservices/homeassistant/restart" % HASS_API, headers=headers, method='POST')
```

Because 127.0.0.1 will be banned all the time due to failed logins. ` headers["x-ha-access"]`only applies to the HASS restart right?

**Comment by danielperna84** [comment]
Does HASS ban failed requests to the API? Besides that, having set the API password should actually not result in failed requests. I've took the `x-ha-access` from the HASS documentation and assumed it would work.

**Comment by tringler** [comment]
Forget what I wrote - It makes no sense because api/bootstrap is also using the header and it's working - I get the data. It is a good question what is causing the bans.

**Comment by danielperna84** [comment]
bootstrap does not quire authentication though. So you still might be correct that there's something wrong there.

**Comment by tringler** [comment]
I will take a deeper look tomorrow.

**Comment by danielperna84** [comment]
I had a look at it myself now.

Scenario 1 (no SSL, but API password set for configurator):
```
Starting server
Listening on: http://192.168.1.21:3218
192.168.1.30 - - [01/Feb/2017 01:01:26] "GET / HTTP/1.1" 200 -
<urlopen error [Errno 0] Error>
192.168.1.30 - - [01/Feb/2017 01:01:26] "GET /api/files HTTP/1.1" 200 -
192.168.1.30 - - [01/Feb/2017 01:01:27] "GET /favicon.ico HTTP/1.1" 200 -
<urlopen error [Errno 0] Error>
```

Scenario 2 (with SSL and with & without API password):
```
Starting server
Listening on: https://192.168.1.21:3218
192.168.1.30 - - [01/Feb/2017 01:04:39] "GET / HTTP/1.1" 200 -
<urlopen error [Errno -2] Name or service not known>
192.168.1.30 - - [01/Feb/2017 01:04:39] "GET /api/files HTTP/1.1" 200 -
192.168.1.30 - - [01/Feb/2017 01:04:39] "GET /favicon.ico HTTP/1.1" 200 -
<urlopen error [Errno -2] Name or service not known>
```

My first scenario is irritating me at the moment since I haven't seen that before. Although that could also be a result of my current progress with another feature (optional persistent settings in an external file, makes future updates easier).

**Comment by danielperna84** [comment]
The `Name or service not known`is a result of a failing request to my repo which fetches the latest release version to notify about updates. So nothing crucial. The reason they came up twice because there was no 404-handler. The favicon the browser tries to fetch does not exist, which resulted in generating the full index, which then also again fetched the bootstrap data and the latest release. Will be fixed soon.

There's still an error with the API_PASSWORD though. But I'll do that tomorrow.

**Comment by danielperna84** [comment]
I've got rid of the chroot workaround. Could you please test the latest version? I have tested everything except restarting HASS (can't do that right now because of the others at home), and I don't get any errors anymore, no matter if using SSL or not.

**Comment by tringler** [comment]
I can confirm, that the `Name or service not known` are gone and the solution is working with systemd like a charm. I really appreciate your work 👍 

I will close issue, because it's all solved.
